
from keras.models import model_from_json
import coremltools
import globalData
globalData.init()

def exportToCoreML(fileName):
    # load json and create model
    json_file = open('src/model.json', 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    model = model_from_json(loaded_model_json)
    # load weights into new model
    model.load_weights("src/model.h5")
    print("Loaded model from disk")

    coreMLModel = coremltools.converters.keras.convert(model, input_names = ['workoutSummary'],
                                                             output_names = ['probabilities'],
                                                             class_labels = globalData.CLASSIFICATIONS,
                                                   predicted_feature_name = 'classification')
    coreMLModel.author = 'Chappy Asel'
    coreMLModel.license = 'MIT'
    coreMLModel.short_description = 'Determines a workout name based on the workout summary'
    coreMLModel.input_description['workoutSummary'] = 'The summary generated by the workout divided into a body split array'
    coreMLModel.output_description['probabilities'] = 'The probabilities of each classification'
    coreMLModel.output_description['classification'] = 'The Most likely workout classification'
    coreMLModel.save(fileName)
